### ISSUE TITLE
Cannot find -lvitashaders and -lAdrenalineKernel_stub

### ISSUE THREAD

**Issue by polaris-dxz** [frangarcj/libvita2d#1]
I installed libvita2d,
And I copied the vita-shader-collection library and includes to usr/local/vitasdk/arm-vita-eabi,
But the terminal still prompts me cannot find -lvitashaders and -lAdrenalineKernel_stuberror.

What can I do to properly compile Adrenaline？

**Comment by Yggdrasill-7C9** [comment]
Solution：
1. Installed VDPM
2. Installed Adrenaline kernel Library
3. Intalled libvita2d from fbo
4. Copied the vita-shader-collection library and includes to `usr/local/vitasdk/arm-vita-eabi`
